# Generated by Django 2.1.7 on 2019-04-29 13:12

from django.db import migrations, models
import imageUpload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedModel',
            fields=[
                ('name', models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('file', models.ImageField(upload_to=imageUpload.models.modify_and_rename)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=imageUpload.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='name',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
