# Generated by Django 2.1.7 on 2019-05-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0002_auto_20190429_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedmodel',
            name='checked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='checked',
            field=models.BooleanField(default=0),
        ),
    ]
