# Generated by Django 2.1.7 on 2019-05-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0005_cosmetics'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetics',
            name='season',
            field=models.CharField(default='', max_length=10),
        ),
    ]
