# Generated by Django 2.1.7 on 2019-05-08 13:17

from django.db import migrations, models
import imageUpload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0007_make_up_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_up_applied',
            name='id',
        ),
        migrations.AddField(
            model_name='make_up_applied',
            name='name',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='make_up_applied',
            name='file',
            field=models.ImageField(upload_to=imageUpload.models.Applied_and_rename),
        ),
    ]
