# Generated by Django 2.1.7 on 2019-05-08 13:31

from django.db import migrations, models
import imageUpload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0008_auto_20190508_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=imageUpload.models.path_and_rename),
        ),
    ]
