# Generated by Django 2.1.7 on 2019-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0009_auto_20190508_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_up_applied',
            name='file',
            field=models.ImageField(upload_to='output/'),
        ),
    ]
